import type { PlatformSpec } from './platform-import';

// ZID product export -> Requital. THE ONLY PLACE the Zid column names live.
//
// STATUS: EVERY HEADER BELOW IS INFERRED, as for Salla (see salla-import.ts).
// Zid's catalogue is bilingual, so a name and a description may arrive in an
// Arabic and an English column. Requital has one name per product: the
// `name` aliases (English first) win and the Arabic column is the fallback,
// so a file with only an Arabic name still imports. When both are present
// and differ, the merchant is warned that the second was not imported.
// To correct the mapping, edit the arrays below.
export const ZID_SPEC: PlatformSpec = {
  source: 'zid',
  label: 'Zid',
  required: ['name', 'price'],
  aliases: {
    name: [
      'name',
      'product name',
      'product title',
      'title',
      'name en',
      'name english',
      'product name en',
      'product name english',
    ],
    nameAlt: [
      'name ar',
      'name arabic',
      'product name ar',
      'product name arabic',
      'اسم المنتج',
      'الاسم',
    ],
    description: [
      'description',
      'description en',
      'description ar',
      'product description',
      'الوصف',
      'وصف المنتج',
    ],
    price: ['price', 'regular price', 'السعر'],
    salePrice: [
      'sale price',
      'discount price',
      'special price',
      'سعر الخصم',
      'السعر بعد الخصم',
    ],
    compareAtPrice: ['compare at price', 'compare price'],
    cost: ['cost', 'cost price', 'سعر التكلفة'],
    sku: ['sku', 'product sku', 'رمز المنتج'],
    barcode: ['barcode', 'gtin', 'الباركود'],
    quantity: [
      'quantity',
      'stock',
      'stock quantity',
      'qty',
      'الكمية',
      'المخزون',
    ],
    weight: ['weight', 'الوزن'],
    weightUnit: ['weight unit', 'وحدة الوزن'],
    images: [
      'images',
      'image',
      'image url',
      'image urls',
      'image src',
      'الصور',
      'صورة المنتج',
    ],
    category: ['categories', 'category', 'التصنيفات', 'التصنيف'],
    status: [
      'status',
      'is published',
      'published',
      'is active',
      'active',
      'الحالة',
      'حالة المنتج',
    ],
    requiresShipping: [
      'requires shipping',
      'is shippable',
      'needs shipping',
      'يتطلب شحن',
    ],
    taxable: ['is taxable', 'taxable', 'خاضع للضريبة'],
    vendor: ['brand', 'vendor', 'الماركة'],
    productType: ['product type', 'type', 'نوع المنتج'],
    tags: ['tags', 'keywords', 'الوسوم'],
    seoTitle: ['seo title', 'meta title', 'page title'],
    seoDescription: ['seo description', 'meta description'],
    handle: ['slug', 'handle', 'url key'],
    variantImage: ['variant image', 'option image'],
    option1Name: ['option 1 name', 'option name 1', 'attribute 1 name'],
    option2Name: ['option 2 name', 'option name 2', 'attribute 2 name'],
    option3Name: ['option 3 name', 'option name 3', 'attribute 3 name'],
    option1Value: ['option 1 value', 'option value 1', 'attribute 1 value'],
    option2Value: ['option 2 value', 'option value 2', 'attribute 2 value'],
    option3Value: ['option 3 value', 'option value 3', 'attribute 3 value'],
  },
  statuses: {
    available: [
      'active',
      'published',
      'visible',
      'true',
      '1',
      'yes',
      'نشط',
      'ظاهر',
      'منشور',
    ],
    unavailable: [
      'inactive',
      'unpublished',
      'hidden',
      'draft',
      'false',
      '0',
      'no',
      'غير نشط',
      'مخفي',
      'مسودة',
    ],
    archived: ['archived', 'مؤرشف'],
  },
  yes: ['yes', 'true', '1', 'y', 'نعم'],
  no: ['no', 'false', '0', 'n', 'لا'],
  unlimitedQuantity: ['unlimited', 'infinite', '∞', 'غير محدود'],
  weightUnits: {
    kg: ['kg', 'kgs', 'kilogram', 'kilograms', 'كجم', 'كغ', 'كيلو'],
    g: ['g', 'gm', 'gram', 'grams', 'جم', 'غم', 'جرام', 'غرام'],
  },
  variantRowTypes: ['option', 'variant', 'variation', 'خيار'],
};
