-- AlterTable
ALTER TABLE `shop` ADD COLUMN `allowPreOrders` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `asapDeliveryEnabled` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `birthdayDiscountEnabled` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `businessHours` TEXT NULL,
    ADD COLUMN `businessType` VARCHAR(191) NULL,
    ADD COLUMN `customerConfirmationRequired` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `customerSurveyEnabled` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `defaultDeliveryFee` DECIMAL(65, 30) NOT NULL DEFAULT 0,
    ADD COLUMN `defaultLanguage` VARCHAR(191) NOT NULL DEFAULT 'en',
    ADD COLUMN `deliveryCalendarEnabled` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `disableGoogleMaps` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `disableStoreCart` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `dynamicThemeBuilderEnabled` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `externalDeliveryEnabled` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `productAttributesEnabled` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `productDisplayOrientation` VARCHAR(191) NOT NULL DEFAULT 'grid',
    ADD COLUMN `productFaqsEnabled` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `productImageZoomEnabled` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `productVariantsEnabled` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `showCategoryMenu` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `taxDisplayText` VARCHAR(191) NULL,
    ADD COLUMN `whatsappFloatingButtonEnabled` BOOLEAN NOT NULL DEFAULT false;
