// Curated list of popular Google Fonts family names for the theme builder's
// FontPicker — not the full ~1500-font catalog, but real family names that
// work as-is with Google's CSS2 API (fonts.googleapis.com/css2?family=...),
// which the storefront loads dynamically at runtime (see storefront's
// google-fonts loader, Phase 5). A curated list here is just a convenience
// for the dropdown; the storefront's loader isn't restricted to it.
export const GOOGLE_FONTS: string[] = [
  "Inter",
  "Roboto",
  "Open Sans",
  "Lato",
  "Montserrat",
  "Poppins",
  "Source Sans 3",
  "Oswald",
  "Raleway",
  "Nunito",
  "Playfair Display",
  "Merriweather",
  "PT Sans",
  "Noto Sans",
  "Ubuntu",
  "Rubik",
  "Work Sans",
  "Mulish",
  "Karla",
  "Manrope",
  "DM Sans",
  "Fira Sans",
  "Quicksand",
  "Josefin Sans",
  "Space Grotesk",
  "Cormorant Garamond",
  "Libre Baskerville",
  "Crimson Text",
  "EB Garamond",
  "Lora",
  "Bitter",
  "Barlow",
  "Archivo",
  "Inconsolata",
  "Cabin",
  "Dosis",
  "Abril Fatface",
  "Bebas Neue",
  "Pacifico",
  "Caveat",
  "Comfortaa",
];
